export const chanseyquotes = {
  Motivation: [
    'Every great achievement begins with a decision to try. You don’t have to be perfect, just brave enough to start, and persistent enough to keep going.',
    'The path to success is rarely straight. It twists, turns, and sometimes doubles back — but every step forward, no matter how small, still moves you ahead.',
    'Don’t wait for inspiration to strike; build habits that carry you forward when motivation fades.',
    'You’ll never know how capable you are until you stop doubting yourself and begin acting like you already are who you want to become.',
    'Growth feels uncomfortable because you’re becoming someone new. Lean into the discomfort — it’s proof that change is happening.',
    'You don’t need to have it all figured out. Just take one small step forward and trust that the next one will reveal itself.',
    'Every morning is another chance to rewrite your story. Don’t be afraid to start over; it’s a sign of strength, not failure.',
    'There will be days when you don’t feel like showing up — but those are the days that shape your future the most.',
    'Success doesn’t demand perfection; it demands persistence. Keep moving, even when progress feels invisible.',
    'Remember why you started, even when the path gets hard. Your purpose is stronger than your fear.',
  ],
  Productivity: [
    'Productivity is not about doing more — it’s about doing what truly matters. Focus on the few things that move you closer to your purpose.',
    'Start before you’re ready, because ‘ready’ never really comes. Clarity appears through action, not overthinking.',
    'A clear plan is good, but a clear mind is better. Simplify your priorities until what’s left feels peaceful and possible.',
    'Don’t let the pursuit of perfection stop your progress. An imperfect action is worth more than a perfect idea.',
    'Momentum builds from small wins. Celebrate them, because they fuel your next step forward.',
    'When you feel overwhelmed, pause. Breathe. Then do the next simple thing — not everything at once, just one thing.',
    'Productivity isn’t a race; it’s a rhythm. Learn to work with your energy, not against it.',
    'The most successful people aren’t always the busiest — they’re the ones who know what to ignore.',
    'Focus is a skill, not a gift. You strengthen it every time you choose purpose over distraction.',
    'Don’t count the hours you’ve worked; count the value you’ve created.',
  ],
  Mindfulness: [
    'Peace doesn’t mean a life without noise — it means learning to find quiet within yourself, even when the world gets loud.',
    'You don’t need to have all the answers right now. Sometimes the best thing you can do is pause and let clarity find you.',
    'Breathe deeply. You’ve made it through 100% of your hardest days so far — and that’s something to be proud of.',
    'Stillness is not the absence of movement, but the awareness that you can choose how to move.',
    'It’s okay to rest. You’re not losing time — you’re rebuilding the energy you need to continue.',
    'When your mind runs fast, slow down your breath. The body listens, and so will your thoughts.',
    'Let go of the idea that you must be calm all the time. Peace is not perfection; it’s acceptance.',
    'Don’t rush your healing. Growth happens quietly, beneath the surface, before it blooms.',
    'Sometimes the bravest thing you can do is stop fighting and allow yourself to simply be.',
    'The world will wait while you take a moment to breathe.',
  ],
};
